server: 
    port: 10666 #gin启动的端口号
datasource:
    drivename: mysql #数据库使用类型
    host: 10.0.10.27 #数据库主机地址
    port: 33306 #数据库端口
    username: root #用户名
    password: root_unionid #密码
    database: ganlei #数据库名称
    charset: utf8 #数据库字符编码格式